//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testingproviderClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public string Id_H { get; set; }
        public string Id_S { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string StreetSuffix { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Id_R { get; set; }
        public string Space { get; set; }
        public string Id_C { get; set; }
        public string Long { get; set; }
        public string Lat { get; set; }

    }
}
