//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testingproviderClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NextService
    {
        public int Id { get; set; }
        public string DateRange { get; set; }
        public string ServiceDetails { get; set; }
        public string NotesToCustomer { get; set; }
    }
}
