//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testingproviderClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int Id_N { get; set; }
        public bool FromProvider { get; set; }
        public bool FromCustomer { get; set; }
        public string WrittenNote { get; set; }
        public string Id_H { get; set; }
        public Nullable<System.DateTime> Ndate { get; set; }
    }
}
