//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testingproviderClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public string Id_P { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CityTerritory { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNum { get; set; }
    }
}
