//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testingproviderClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoyApp_dbEntities : DbContext
    {
        public CoyApp_dbEntities()
            : base("name=CoyApp_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<House> Houses { get; set; }
        public virtual DbSet<NextService> NextServices { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<Service> Services { get; set; }
    }
}
