//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testingproviderClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int Id_R { get; set; }
        public string DayOfWeek { get; set; }
        public string Id_P { get; set; }
    }
}
